name = "covid-19-presentation"
compatibility_date = "2024-01-15"
pages_build_output_dir = "build"

[build]
command = "npm run build"
cwd = ""

[build.environment_variables]
NODE_VERSION = "18"

[env.production]
account_id = ""  # Add your Cloudflare account ID here
